using System.Text.RegularExpressions;
using Vessel.Application.Evidence;

namespace Vessel.Infrastructure.Evidence;

/// <summary>
/// Keeps evidence objects as files under one root. Writes go to a temporary file first and are
/// moved into place, so readers never see a partial image.
/// </summary>
public sealed partial class LocalEvidenceObjectStore(string rootPath) : IEvidenceObjectStore
{
    private readonly string root = Path.GetFullPath(rootPath);

    public async Task PutAsync(string key, Stream content, CancellationToken ct)
    {
        var path = PathFor(key);
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        var temporary = $"{path}.{Guid.NewGuid():N}.tmp";
        try
        {
            await using (var file = new FileStream(temporary, FileMode.CreateNew, FileAccess.Write, FileShare.None, 81920, FileOptions.Asynchronous))
            {
                await content.CopyToAsync(file, ct);
                await file.FlushAsync(ct);
            }
            File.Move(temporary, path, overwrite: false);
        }
        finally
        {
            if (File.Exists(temporary)) File.Delete(temporary);
        }
    }

    public Task<Stream?> OpenReadAsync(string key, CancellationToken ct)
    {
        try
        {
            return Task.FromResult<Stream?>(new FileStream(PathFor(key), FileMode.Open, FileAccess.Read, FileShare.Read, 81920,
                FileOptions.Asynchronous | FileOptions.SequentialScan));
        }
        catch (Exception error) when (error is FileNotFoundException or DirectoryNotFoundException)
        {
            return Task.FromResult<Stream?>(null);
        }
    }

    public Task DeleteAsync(string key, CancellationToken ct)
    {
        File.Delete(PathFor(key));
        return Task.CompletedTask;
    }

    private string PathFor(string key)
    {
        // Keys are generated by the application; reject anything else rather than normalize it.
        if (!KeyPattern().IsMatch(key)) throw new ArgumentException("Invalid evidence object key.", nameof(key));
        var path = Path.GetFullPath(Path.Combine(root, key));
        if (!path.StartsWith(root + Path.DirectorySeparatorChar, StringComparison.Ordinal))
            throw new ArgumentException("Invalid evidence object key.", nameof(key));
        return path;
    }

    [GeneratedRegex("^[a-z0-9]+(/[a-z0-9]+)*\\.[a-z0-9]+$")]
    private static partial Regex KeyPattern();
}
