<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../Vessel.Domain/Vessel.Domain.csproj" />
    <ProjectReference Include="../Vessel.Application/Vessel.Application.csproj" />
  </ItemGroup>
  <ItemGroup><PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.10" /></ItemGroup>
  <ItemGroup><PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10" PrivateAssets="all" /></ItemGroup>
  <ItemGroup><PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" /></ItemGroup>
  <ItemGroup><PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.10" /></ItemGroup>
</Project>
