using System.Text.Json.Serialization;
using Vessel.Domain.Evidence;
using Vessel.Domain.Plays;

namespace Vessel.Application.Evidence;

public sealed record EvidenceDto(Guid Id, Guid PlayId, string Source, string ContentType, long SizeBytes, string Sha256,
    string Note, DateTimeOffset CreatedAtUtc, DateTimeOffset UpdatedAtUtc, ImageMarkup? Markup);
public sealed record UpdateEvidenceNoteRequest([property: JsonRequired] string Note);
public sealed record EvidenceContent(Stream Content, string ContentType, long SizeBytes, string Sha256);

/// <summary>Upload limits; composition binds them from configuration.</summary>
public sealed record EvidenceLimits(long MaxUploadBytes, int MaxPerPlay)
{
    public static readonly EvidenceLimits Default = new(10 * 1024 * 1024, 50);
}

/// <summary>
/// Stores evidence image bytes under keys generated by the application. Implementations are
/// selected by configuration: the local filesystem now, an S3-compatible store later. Authorization
/// and metadata stay in the application; a store never sees owners, Plays or notes.
/// </summary>
public interface IEvidenceObjectStore
{
    /// <summary>Writes a new object. Keys are never reused, so an existing key is an error.</summary>
    Task PutAsync(string key, Stream content, CancellationToken ct);
    /// <summary>Opens the object for reading, or null when it does not exist.</summary>
    Task<Stream?> OpenReadAsync(string key, CancellationToken ct);
    /// <summary>Deletes the object; a missing object is not an error.</summary>
    Task DeleteAsync(string key, CancellationToken ct);
}

// Application owns this bounded port; EF details stay in Persistence. Reads are owner-filtered.
public interface IEvidenceMetadataStore
{
    Task<Play?> PlayAsync(Guid playId, CancellationToken ct);
    Task<List<PlayEvidence>> ListAsync(Guid playId, CancellationToken ct);
    Task<int> CountAsync(Guid playId, CancellationToken ct);
    Task<PlayEvidence?> FindAsync(Guid id, CancellationToken ct);
    Task AddAsync(PlayEvidence evidence, CancellationToken ct);
    Task RemoveAsync(PlayEvidence evidence, CancellationToken ct);
    Task SaveAsync(CancellationToken ct);
}
