// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Vessel.Persistence;

#nullable disable

namespace Vessel.Persistence.Migrations
{
    [DbContext(typeof(VesselDbContext))]
    [Migration("20261001125452_StablecoinWallet")]
    partial class StablecoinWallet
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Vessel.Domain.Accounts.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(42)
                        .HasColumnType("character varying(42)");

                    b.Property<string>("HistoryNotice")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("LastSyncError")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("LastSyncedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("ManualAccountValueUsd")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PortfolioId")
                        .HasColumnType("uuid");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("VenueId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "PortfolioId");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("Vessel.Domain.Plays.Play", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContractId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("VenueId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "AccountId", "VenueId", "ContractId");

                    b.ToTable("plays", (string)null);
                });

            modelBuilder.Entity("Vessel.Domain.Workspace.AccountPosition", b =>
                {
                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContractId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<decimal>("EntryPrice")
                        .HasColumnType("numeric");

                    b.Property<int?>("Leverage")
                        .HasColumnType("integer");

                    b.Property<decimal>("MarginUsedUsd")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SignedQuantity")
                        .HasColumnType("numeric");

                    b.Property<decimal>("UnrealizedPnlUsd")
                        .HasColumnType("numeric");

                    b.HasKey("OwnerId", "AccountId", "ContractId");

                    b.ToTable("account_positions", (string)null);
                });

            modelBuilder.Entity("Vessel.Domain.Workspace.AccountSnapshot", b =>
                {
                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("AccountMode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal?>("AccountValueUsd")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MarginUsedUsd")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("ObservedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StablecoinScope")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("StablecoinsObservedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ValueScope")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<decimal?>("WithdrawableUsd")
                        .HasColumnType("numeric");

                    b.HasKey("OwnerId", "AccountId");

                    b.ToTable("account_snapshots", (string)null);
                });

            modelBuilder.Entity("Vessel.Domain.Workspace.AccountStablecoin", b =>
                {
                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("TokenId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal>("Available")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Held")
                        .HasColumnType("numeric");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("TokenIndex")
                        .HasColumnType("integer");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.HasKey("OwnerId", "AccountId", "TokenId");

                    b.ToTable("account_stablecoins", (string)null);
                });

            modelBuilder.Entity("Vessel.Domain.Workspace.ImportedFill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ClosedPnlUsd")
                        .HasColumnType("numeric");

                    b.Property<string>("ContractId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<decimal>("Fee")
                        .HasColumnType("numeric");

                    b.Property<string>("FeeToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SourceFillId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TransactionHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "OccurredAtUtc");

                    b.HasIndex("OwnerId", "AccountId", "ContractId", "SourceFillId")
                        .IsUnique();

                    b.ToTable("imported_fills", (string)null);
                });

            modelBuilder.Entity("Vessel.Domain.Workspace.Portfolio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("portfolios", (string)null);
                });

            modelBuilder.Entity("Vessel.Domain.Accounts.Account", b =>
                {
                    b.HasOne("Vessel.Domain.Workspace.Portfolio", null)
                        .WithMany()
                        .HasForeignKey("OwnerId", "PortfolioId")
                        .HasPrincipalKey("OwnerId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Vessel.Domain.Plays.Play", b =>
                {
                    b.HasOne("Vessel.Domain.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("OwnerId", "AccountId")
                        .HasPrincipalKey("OwnerId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Vessel.Domain.Workspace.AccountPosition", b =>
                {
                    b.HasOne("Vessel.Domain.Workspace.AccountSnapshot", null)
                        .WithMany("Positions")
                        .HasForeignKey("OwnerId", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vessel.Domain.Workspace.AccountSnapshot", b =>
                {
                    b.HasOne("Vessel.Domain.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("OwnerId", "AccountId")
                        .HasPrincipalKey("OwnerId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Vessel.Domain.Workspace.AccountStablecoin", b =>
                {
                    b.HasOne("Vessel.Domain.Workspace.AccountSnapshot", null)
                        .WithMany("Stablecoins")
                        .HasForeignKey("OwnerId", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vessel.Domain.Workspace.ImportedFill", b =>
                {
                    b.HasOne("Vessel.Domain.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("OwnerId", "AccountId")
                        .HasPrincipalKey("OwnerId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Vessel.Domain.Workspace.AccountSnapshot", b =>
                {
                    b.Navigation("Positions");

                    b.Navigation("Stablecoins");
                });
#pragma warning restore 612, 618
        }
    }
}
