// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Vessel.Persistence;

#nullable disable

namespace Vessel.Persistence.Migrations
{
    [DbContext(typeof(VesselDbContext))]
    [Migration("20261007184302_HyperliquidCanonicalInstruments")]
    partial class HyperliquidCanonicalInstruments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Vessel.Domain.Accounts.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(42)
                        .HasColumnType("character varying(42)");

                    b.Property<string>("HistoryNotice")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("LastSyncError")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("LastSyncedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("ManualAccountValueUsd")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PortfolioId")
                        .HasColumnType("uuid");

                    b.Property<long>("SettingsRevision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L);

                    b.Property<string>("SourceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("VenueId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "PortfolioId");

                    b.HasIndex("OwnerId", "VenueId", "SourceId")
                        .IsUnique()
                        .HasDatabaseName("UX_accounts_owner_venue_source")
                        .HasFilter("\"SourceId\" IS NOT NULL");

                    b.ToTable("accounts", null, t =>
                        {
                            t.HasCheckConstraint("CK_accounts_normalized_address", "\"Address\" IS NULL OR \"Address\" = lower(\"Address\")");

                            t.HasCheckConstraint("CK_accounts_settings_revision", "\"SettingsRevision\" >= 1");

                            t.HasCheckConstraint("CK_accounts_source_identity", "(\"Address\" IS NULL OR \"SourceId\" IS NOT NULL AND \"SourceId\" = \"Address\") AND CASE WHEN \"SourceId\" IS NULL OR \"Address\" IS NOT NULL THEN true WHEN \"SourceId\" ~ '^(0|[1-9][0-9]{0,18})$' THEN \"SourceId\"::numeric <= 9223372036854775807 ELSE false END");
                        });
                });

            modelBuilder.Entity("Vessel.Domain.Credentials.AccountCredential", b =>
                {
                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("Purpose")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<byte[]>("Ciphertext")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("KeyId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("LastError")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("LastVerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("Nonce")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<byte[]>("Tag")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("OwnerId", "AccountId", "Purpose");

                    b.ToTable("account_credentials", null, t =>
                        {
                            t.HasCheckConstraint("CK_account_credentials_envelope", "octet_length(\"Nonce\") = 12 AND octet_length(\"Tag\") = 16 AND octet_length(\"Ciphertext\") BETWEEN 1 AND 2048");

                            t.HasCheckConstraint("CK_account_credentials_scope", "\"Scope\" IN ('single', 'all')");
                        });
                });

            modelBuilder.Entity("Vessel.Domain.Evidence.PlayEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Markup")
                        .HasColumnType("jsonb");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayId")
                        .HasColumnType("uuid");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ObjectKey")
                        .IsUnique();

                    b.HasIndex("OwnerId", "PlayId", "CreatedAtUtc");

                    b.ToTable("play_evidence", null, t =>
                        {
                            t.HasCheckConstraint("CK_play_evidence_sha256", "\"Sha256\" ~ '^[0-9a-f]{64}$'");

                            t.HasCheckConstraint("CK_play_evidence_size", "\"SizeBytes\" > 0");
                        });
                });

            modelBuilder.Entity("Vessel.Domain.Plays.Play", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("ContractId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Drawings")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("EndedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InstrumentSource")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("PlanRevision")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("PlannedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Review")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VenueId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "UpdatedAtUtc");

                    b.HasIndex("OwnerId", "AccountId", "VenueId", "ContractId");

                    b.ToTable("plays", (string)null);
                });

            modelBuilder.Entity("Vessel.Domain.Plays.PlayOrderLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EntryId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("LevelId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "PlayId");

                    b.HasIndex("OwnerId", "AccountId", "OrderId")
                        .IsUnique()
                        .HasDatabaseName("UX_play_order_links_linked_order")
                        .HasFilter("\"State\" = 'Linked'");

                    b.ToTable("play_order_links", (string)null);
                });

            modelBuilder.Entity("Vessel.Domain.Plays.PlayPlanRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("PlayId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "PlayId", "Number")
                        .IsUnique();

                    b.ToTable("play_plan_revisions", null, t =>
                        {
                            t.HasCheckConstraint("CK_play_plan_revisions_number", "\"Number\" >= 1");
                        });
                });

            modelBuilder.Entity("Vessel.Domain.Plays.PlayStatusChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("Owner");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "PlayId", "OccurredAtUtc");

                    b.ToTable("play_status_changes", (string)null);
                });

            modelBuilder.Entity("Vessel.Domain.Sizing.SizingSettings", b =>
                {
                    b.Property<Guid>("OwnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("RiskPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("OwnerId");

                    b.ToTable("sizing_settings", null, t =>
                        {
                            t.HasCheckConstraint("CK_sizing_settings_risk", "\"RiskPercent\" >= 0.1 AND \"RiskPercent\" <= 5");
                        });
                });

            modelBuilder.Entity("Vessel.Domain.Workspace.AccountPosition", b =>
                {
                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContractId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<decimal>("EntryPrice")
                        .HasColumnType("numeric");

                    b.Property<int?>("Leverage")
                        .HasColumnType("integer");

                    b.Property<decimal>("MarginUsedUsd")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SignedQuantity")
                        .HasColumnType("numeric");

                    b.Property<decimal>("UnrealizedPnlUsd")
                        .HasColumnType("numeric");

                    b.Property<string>("VenueContractId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("OwnerId", "AccountId", "ContractId");

                    b.ToTable("account_positions", (string)null);
                });

            modelBuilder.Entity("Vessel.Domain.Workspace.AccountSnapshot", b =>
                {
                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("AccountMode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal?>("AccountValueUsd")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MarginUsedUsd")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("ObservedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StablecoinScope")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("StablecoinsObservedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ValueScope")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<decimal?>("WithdrawableUsd")
                        .HasColumnType("numeric");

                    b.HasKey("OwnerId", "AccountId");

                    b.ToTable("account_snapshots", (string)null);
                });

            modelBuilder.Entity("Vessel.Domain.Workspace.AccountStablecoin", b =>
                {
                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("TokenId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal>("Available")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Held")
                        .HasColumnType("numeric");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("TokenIndex")
                        .HasColumnType("integer");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.HasKey("OwnerId", "AccountId", "TokenId");

                    b.ToTable("account_stablecoins", (string)null);
                });

            modelBuilder.Entity("Vessel.Domain.Workspace.ImportedFill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ClosedPnlUsd")
                        .HasColumnType("numeric");

                    b.Property<string>("ContractId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<decimal>("Fee")
                        .HasColumnType("numeric");

                    b.Property<string>("FeeBasis")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("FeeToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("PnlBasis")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("PositionEffect")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SourceFillId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TransactionHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("VenueContractId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "OccurredAtUtc");

                    b.HasIndex("OwnerId", "AccountId", "ContractId", "SourceFillId")
                        .IsUnique();

                    b.ToTable("imported_fills", null, t =>
                        {
                            t.HasCheckConstraint("CK_imported_fills_fee_basis", "\"FeeBasis\" IN ('reported', 'standard-account-free')");

                            t.HasCheckConstraint("CK_imported_fills_pnl_basis", "\"PnlBasis\" IN ('gross', 'net-of-fee')");

                            t.HasCheckConstraint("CK_imported_fills_position_effect", "\"PositionEffect\" IN ('open', 'close', 'flip', 'unknown')");

                            t.HasCheckConstraint("CK_imported_fills_side", "\"Side\" IN ('buy', 'sell')");
                        });
                });

            modelBuilder.Entity("Vessel.Domain.Workspace.ImportedOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContractId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsPositionTpsl")
                        .HasColumnType("boolean");

                    b.Property<decimal>("LimitPrice")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("ObservedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal>("OriginalSize")
                        .HasColumnType("numeric");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("PlacedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ReduceOnly")
                        .HasColumnType("boolean");

                    b.Property<decimal>("RemainingSize")
                        .HasColumnType("numeric");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("StatusAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("TriggerPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("VenueContractId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("VenueStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "AccountId", "OrderId")
                        .IsUnique();

                    b.ToTable("imported_orders", null, t =>
                        {
                            t.HasCheckConstraint("CK_imported_orders_side", "\"Side\" IN ('buy', 'sell')");
                        });
                });

            modelBuilder.Entity("Vessel.Domain.Workspace.Portfolio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("portfolios", (string)null);
                });

            modelBuilder.Entity("Vessel.Domain.Accounts.Account", b =>
                {
                    b.HasOne("Vessel.Domain.Workspace.Portfolio", null)
                        .WithMany()
                        .HasForeignKey("OwnerId", "PortfolioId")
                        .HasPrincipalKey("OwnerId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Vessel.Domain.Credentials.AccountCredential", b =>
                {
                    b.HasOne("Vessel.Domain.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("OwnerId", "AccountId")
                        .HasPrincipalKey("OwnerId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vessel.Domain.Evidence.PlayEvidence", b =>
                {
                    b.HasOne("Vessel.Domain.Plays.Play", null)
                        .WithMany()
                        .HasForeignKey("OwnerId", "PlayId")
                        .HasPrincipalKey("OwnerId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Vessel.Domain.Plays.Play", b =>
                {
                    b.HasOne("Vessel.Domain.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("OwnerId", "AccountId")
                        .HasPrincipalKey("OwnerId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Vessel.Domain.Plays.PlayOrderLink", b =>
                {
                    b.HasOne("Vessel.Domain.Plays.Play", null)
                        .WithMany()
                        .HasForeignKey("OwnerId", "PlayId")
                        .HasPrincipalKey("OwnerId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Vessel.Domain.Plays.PlayPlanRevision", b =>
                {
                    b.HasOne("Vessel.Domain.Plays.Play", null)
                        .WithMany()
                        .HasForeignKey("OwnerId", "PlayId")
                        .HasPrincipalKey("OwnerId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Vessel.Domain.Plays.PlayStatusChange", b =>
                {
                    b.HasOne("Vessel.Domain.Plays.Play", null)
                        .WithMany()
                        .HasForeignKey("OwnerId", "PlayId")
                        .HasPrincipalKey("OwnerId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Vessel.Domain.Workspace.AccountPosition", b =>
                {
                    b.HasOne("Vessel.Domain.Workspace.AccountSnapshot", null)
                        .WithMany("Positions")
                        .HasForeignKey("OwnerId", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vessel.Domain.Workspace.AccountSnapshot", b =>
                {
                    b.HasOne("Vessel.Domain.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("OwnerId", "AccountId")
                        .HasPrincipalKey("OwnerId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Vessel.Domain.Workspace.AccountStablecoin", b =>
                {
                    b.HasOne("Vessel.Domain.Workspace.AccountSnapshot", null)
                        .WithMany("Stablecoins")
                        .HasForeignKey("OwnerId", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vessel.Domain.Workspace.ImportedFill", b =>
                {
                    b.HasOne("Vessel.Domain.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("OwnerId", "AccountId")
                        .HasPrincipalKey("OwnerId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Vessel.Domain.Workspace.ImportedOrder", b =>
                {
                    b.HasOne("Vessel.Domain.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("OwnerId", "AccountId")
                        .HasPrincipalKey("OwnerId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Vessel.Domain.Workspace.AccountSnapshot", b =>
                {
                    b.Navigation("Positions");

                    b.Navigation("Stablecoins");
                });
#pragma warning restore 612, 618
        }
    }
}
